---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: devops-training-281306
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/rsehgal/devops-training-281306-a5aae0650847.json
      zone: "us-central1-a"
      region: "us-central1"
      tag1: "{{ tag1 }}"
  tasks:
  - debug: msg="the echo was {{ tag }}"
  - debug: msg="the echo was {{ tag1 }}"
    #command: /bin/sh './scripts/part1_create_vm.sh'
    #- debug: msg="the echo was {{ role_path }}/files/part1_create_vm.sh"
